### PR TITLE
cleaned up broken API endpoints

### PR DESCRIPTION
**Pull request by nevaan9**
re #35676

### CODE REVIEW

**Comment by gabaum10** [comment]
@nevaan, let me merge this PR for you.  There is a special syntax that you need to follow to get the build working

**Comment by nevaan9** [comment]
Okay, thanks @gabaum10

**Comment by gabaum10** [comment]
@nevaan9 make sure that you remember to run `yarn upgrade @greywallsoftware/veoci-js` in the Vue project to make sure the changes are set for the live deployed version.

**Comment by gabaum10** [comment]
Oh, wait for the mom version is published before you do that.

**Comment by gabaum10** [comment]
And it is, so run that and cmit the yarn.lock changes for the Vue project.

**Pull request merged**
